# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'kangyuanhuihang' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kangyuanhuihang

  target 'kangyuanhuihangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kangyuanhuihangUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry'
pod 'AFNetworking'

end
